linters:
  enable:
    - dogsled
    - dupl
    - goconst
    - goimports
    - golint
    - prealloc
    - staticcheck
    - unconvert
    - unused

issues:
  # Disable max issues
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - text: "SA1019:"
      linters:
        - staticcheck
