linters:
  fast: true
  enable:
    - dogsled
    - dupl
    - goconst
    - golint
    - prealloc
    - unconvert
    - unused

issues:
  # Disable max issues
  max-issues-per-linter: 0
  max-same-issues: 0
