linters:
  enable:
    - dogsled
    - dupl
    - goconst
    - gofmt
    - goimports
    - golint
    - gosimple
    - prealloc
    - staticcheck
    - unconvert
    - unused
    - wsl

issues:
  # Disable max issues
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - text: "SA1019:"
      linters:
        - staticcheck
    - text: "Error return value of `w.Write` is not checked"
      linters:
        - errcheck
run:
  skip-dirs:
    - node_modules
