name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Install Mage
      uses: nickhstr/action-setup-mage@v1.0.0
      with:
        version: 1.9.0

    - name: Download Dependencies
      run: mage install

    - name: Lint
      run: mage lint

    - name: Test
      run: mage coverage
